### ISSUE TITLE
Could not detect abi for version 6.0.0 and runtime electron

### ISSUE THREAD

**Issue by ottosson** [desktop/registry-js#166]
Hi

I just updated my electron project from 5 to 6 and get the following error when running npm install:

```
> node postinstall

  • electron-builder  version=21.2.0
  • loaded configuration  file=C:\project\electron-builder.json
  • rebuilding native dependencies  dependencies=registry-js@1.8.0 platform=win32 arch=x64
  • install prebuilt binary  name=registry-js version=1.8.0 platform=win32 arch=x64
  • build native dependency from sources  name=registry-js
                                          version=1.8.0
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=C:\project\node_modules\node-abi\index.js:30
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 6.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
...
```

I have removed my node_modules folder and updated to the latest version of registry-js (1.8.0) but still get the error. Not sure if I have missed something else... Any suggestion?

**Comment by shiftkey** [comment]
@ottosson thanks for the report! I'm not sure offhand because I thought #165 would address this, and it was included with `1.8.0` which you seem to be using.

Check you don't also have a `node-abi` dependency in your project that might be older than the current version. If you do ensure that you bump it to `2.10.0` which contains the Electron 6 update.

**Comment by ottosson** [comment]
I don't have node-abi in my package.json

**Comment by ottosson** [comment]
Ok so coming back to this issue again I tried to add node-abi (currently 2.11.0) as a dependency for my project and it works! I thought the node-abi would be added by another dependency, (maybe registry-js?), but it seems I was wrong. This fixes the issue for me.

Closing!

**Comment by ottosson** [comment]
Ah, makes sense! Thanks for the explanation.

**Comment by yagoubigithub** [comment]
update node-abi work for me
`yarn upgrade node-abi`
