### ISSUE TITLE
How to require it in node module syntax

### ISSUE THREAD

**Issue by yanlinsun** [desktop/registry-js#167]
I get syntax error if i use this syntax:
`import { enumerateValues, HKEY, RegistryValueType } from 'registry-js'`

How can I use the module like below?
`const { enumerateValues, HKEY, RegistryValueType } = require('registry-js');`

I am writing an electron application. All source codes are written in node require style, uses module.exports. Could anyone help me?

**Comment by j-f1** [comment]
Does he Node module syntax not work for you?

**Comment by yanlinsun** [comment]
No. 
It says 'Module did not self-register' if I use node module syntax.
My node version is 10.15.3
Electron version 6.0.3

**Comment by shiftkey** [comment]
> It says 'Module did not self-register' if I use node module syntax.

@yanlinsun I believe this is a different error, and I wrote some notes about understanding the issue over in https://github.com/atom/node-keytar/issues/215#issuecomment-522343940 because I think your setup is leading to the wrong version being chosen by `prebuild`.

**Comment by yanlinsun** [comment]
@shiftkey I tried the electron-rebuild but no luck. I even tried different registry-js versions, not working. 
Actually, the node module requires syntax does working if I run 'renderer.js' with node. But it seems not working with electron. 
I test using electron-quick-start project and registry-js only, I have attached the project. Also, there are logs of installing registry-js. Would you take a look? Thanks. 
[electron-quick-start.zip](https://github.com/desktop/registry-js/files/3538701/electron-quick-start.zip)

**Comment by shiftkey** [comment]
> Actually, the node module requires syntax does working if I run 'renderer.js' with node. But it seems not working with electron.

This is unsurprising, because of mismatches between Node and Electron that aren't being handled correctly.

From the `registry-js-1.8.0-install.log` file, here's the failure fo 1.8.0:

```
prebuild-install info begin Prebuild-install version 5.3.0
prebuild-install info looking for cached prebuild @ C:\Users\ysun\AppData\Roaming\npm-cache\_prebuilds\e4858a-registry-js-v1.8.0-node-v64-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\ysun\AppData\Roaming\npm-cache\_prebuilds\e4858a-registry-js-v1.8.0-node-v64-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\ysun\Workspaces\Private\electron-quick-start\node_modules\registry-js\build\Release\registry.node
prebuild-install WARN install Module did not self-register.
```

Notice how this is choosing registry-js-v1.8.0-**node-v64**-win32-x64.tar.gz - that's not the right file at all. The rest of the file is it trying to build the native module against node 10.15.3 which I guess is the version you have installed currently.

It's not clear to me how that you're using `electron-rebuild` correctly - it needs to be run after installing any packages but before you launch the app. I think that's the missing part here.

**Comment by yanlinsun** [comment]
### Failed attempts 1
I did run electron-rebuild right after I install registry-js, then run ```npm start```. 
```
$ ./node_modules/.bin/electron-rebuild -f -v 6.0.3 -w registry-js
- Searching dependency tree
√ Rebuild Complete
```
But the error is still the same. I notice that the files in ```node_modules/registry-js``` does not change at all after I run the electron-rebuild. I tried to run using electron-rebuild.cmd, not work either.

### Failed attempts 2
I tried to rename the registry-js-v1.8.0-electron-**v73**-win32-x64.tar.gz to registry-js-v1.8.0-electron-**v64**-win32-x64.tar.gz. Then copy it into ```npm-cache/_prebuilds``` folder. But it does not work. 

### Working version
After some tweak, I managed to get a working version. This is what I did.
1. clone registry-js from github
2. ```npm run electron-prebuild```
3. ```cp build/Release/registry.node ../electron-quick-start/node_modules/registry-js/build/Release```
Then it finally worked in electron.

### Conclusion
I believe this is because of the ```npm install``` compiles the ```registry.node``` against node not electron. But how this happens I do not know. And the electron-rebuild seems not doing anything as the file never touched. Is there any setting wrong in my environment?

**Comment by yanlinsun** [comment]
I find out that the electron-rebuid only work if I put 'registry-js' in "dependencies" section in package.json. It does not work if I put is under 'devDependenies' section.

**Comment by yanlinsun** [comment]
I didn't use the electron-rebuild correctly. By default, it looks for productive dependencies and rebuilds. 
To use electron-rebuild for 'devDependencies', use the following command:
./node_modules/.bin/electron-rebuild -t dev
