### ISSUE TITLE
Editing the Registry

### ISSUE THREAD

**Issue by LOHT03** [desktop/registry-js#169]
Hello,

Does this package allow for mutating/editing values/keys in the registry? Looking through the documentation, it does not seem so.

Thanks.

**Comment by shiftkey** [comment]
@LOHT03 not currently - we have a couple of open issues for mutation to start exploring that #2 #3 

Please open a fresh issue if there are specific things you would like to see supported in this library. 
For example, I suspect [`RegSetKeyValueW `](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regsetkeyvaluew) is an API that might be relevant to your interests.
