### ISSUE TITLE
strings returned for REG_SZ and REG_EXPAND_SZ are not UTF-8

### ISSUE THREAD

**Issue by shiftkey** [desktop/registry-js#17]
<img width="543" src="https://user-images.githubusercontent.com/359239/33531459-827b9104-d8e1-11e7-9c24-d212ba757420.png">

**Comment by joshaber** [comment]
![giphy-3](https://user-images.githubusercontent.com/13760/33552501-1175024c-d8c3-11e7-861e-a0ce36e6793e.gif)
