### ISSUE TITLE
Add support for Electron 7

### ISSUE THREAD

**Issue by ottosson** [desktop/registry-js#170]
https://github.com/electron/electron/releases/tag/v7.0.0

I don't have a clue what's needed to make registry-js work with Electron 7, but just looking at #164 it looks like it is as simple as just adding `-t 7.0.0` to `prebuild-electron` and `prebuild-electron-ia32` and update the `node-abi` dependency?

Is there something else that's needed?

**Comment by shiftkey** [comment]
> Is there something else that's needed?

Nope, that's it. 

We may need also to bump `node-abi` as I can see https://github.com/lgeiger/node-abi/commit/efa7539788036c039132ce0385068a49c084ea51 has been published. That will ensure `prebuild` and `prebuild-install` can detect Electron 7.

**Comment by shiftkey** [comment]
This is now available in [`v1.9.0`](https://github.com/desktop/registry-js/releases/tag/v1.9.0) on NPM.

**Comment by ottosson** [comment]
I get an error when trying to run my project using Electron 7:

> Error: Could not detect abi for version 7.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

I have made sure the latest version of node-abi is installed in my node_modules.

**Comment by shiftkey** [comment]
@ottosson this really feels like #166 again and `prebuild-install` not finding the latest version.

**Comment by ottosson** [comment]
There were some issue with electron-rebuild. I know it's not necessary (from the warnings) but for some reason I needed it a while back for registry-js to build (don't know why 😑) and I've left it in the project since. Removing it seems to solve the issue.

Moving on! 😊
