### ISSUE TITLE
Address double-cast in ReadValues

### ISSUE THREAD

**Issue by shiftkey** [desktop/registry-js#21]
```
..\src\main.cc(161): warning C4244: 'initializing': conversion from 'double' to 'ULONG', possible loss of data [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
..\src\main.cc(166): warning C4312: 'type cast': conversion from 'ULONG' to 'HKEY' of greater size [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
     Creating library C:\projects\lean-mean-registry-client\build\Release\registry.lib and object C:\projects\lean-mean-registry-client\build\Release\registry.exp
```

This was some lazy code to get this up and running sooner - we can do better.

From the JS side, I've got a lookup that converts the string enum to the `long` specified in MSDN:

https://github.com/desktop/registry-js/blob/50dd82ef2ea9c93560c8d4ead14aa72f5bc51bda/lib/registry.ts#L70-L83

Then, in the C++ side, we need to cast this to a `HKEY` to use it with `RegOpenKeyEx`:

https://github.com/desktop/registry-js/blob/7b0da431a747b7093670e6a9b23b282707062bf7/src/main.cc#L152-L161

These look like this in `winreg.h`:

```c++
#define HKEY_CLASSES_ROOT                   (( HKEY ) (ULONG_PTR)((LONG)0x80000000) )
#define HKEY_CURRENT_USER                   (( HKEY ) (ULONG_PTR)((LONG)0x80000001) )
#define HKEY_LOCAL_MACHINE                  (( HKEY ) (ULONG_PTR)((LONG)0x80000002) )
#define HKEY_USERS                          (( HKEY ) (ULONG_PTR)((LONG)0x80000003) )
#define HKEY_PERFORMANCE_DATA               (( HKEY ) (ULONG_PTR)((LONG)0x80000004) )
#define HKEY_PERFORMANCE_TEXT               (( HKEY ) (ULONG_PTR)((LONG)0x80000050) )
#define HKEY_PERFORMANCE_NLSTEXT            (( HKEY ) (ULONG_PTR)((LONG)0x80000060) )
```

Just need to figure out how to marshal these properly from V8's types...

**Comment by danilaml** [comment]
@shiftkey btw, any reason `HKEY` enum holds strings, instead of values directly? Wouldn't need the clumsy `mapToLong` that way. (I've also found this package that does similar stuff: https://github.com/CatalystCode/windows-registry-node )

**Comment by shiftkey** [comment]
> btw, any reason `HKEY` enum holds strings, instead of values directly?

Convenience mostly. A string is a bit more readable for the caller to manage, so this:

```
import { enumerateValues, HKEY } from 'registry-js'

const values = enumerateValues(
  HKEY.HKEY_LOCAL_MACHINE,
  'SOFTWARE\\Microsoft\\Windows\\CurrentVersion'
)
```

Could just be written as this:

```
import { enumerateValues } from 'registry-js'

const values = enumerateValues(
  'HKEY_LOCAL_MACHINE',
  'SOFTWARE\\Microsoft\\Windows\\CurrentVersion'
)
```

**Comment by danilaml** [comment]
@shiftkey well, not sure if it's a good choice when the input value is an enum, i.e. can only be something of few predefined types. This saves only 3 chars to type but makes it easier to make a mistake, IMHO (in both, userCode and mapToLong). But whatever, I don't mind. Just asked)

**Comment by shiftkey** [comment]
@danilaml no problem at all - it's early days for this and I'm basing this off my experiences working with the registry...

**Comment by j-f1** [comment]
@shiftkey enums appear in the compiled JS:

```ts
// from:
enum Foo {
  A = 'A',
  B = 'B',
  C = 'C',
}

// to:
var Foo;
(function (Foo) {
    Foo["A"] = "A";
    Foo["B"] = "B";
    Foo["C"] = "C";
})(Foo || (Foo = {}));
```

([see it live](http://www.typescriptlang.org/play/index.html#src=enum%20Foo%20%7B%0A%20%20A%20%3D%20'A'%2C%0A%20%20B%20%3D%20'B'%2C%0A%20%20C%20%3D%20'C'%2C%0A%7D))
