### ISSUE TITLE
Limit to win32

### ISSUE THREAD

**Issue by linonetwo** [desktop/registry-js#274]
Can you use https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os to limit it to only install (and gpy build) on windows?

Because it breaks mac and linux build, if use with

```json
  "pnpm": {
    "overrides": {
      "node-abi": "latest",
      "prebuild-install": "latest"
    },
```

which is required to fix 

> Error: Could not detect abi for version 28.1.0 and runtime electron. Updating "node-abi" might help solve this issue if it is a new release of electron - Google Search

But if override node-abi to latest, I get error like #224 on mac and linux builds.

**Comment by Rabbitzzc** [comment]
If you use node or Electron, you can use `process.platform` to check if it is in windows. 

then you can use `postintall` to install it..


That's my solution...
