### ISSUE TITLE
Any plans for prebuilt binaries?

### ISSUE THREAD

**Issue by vweevers** [desktop/registry-js#34]
It's fairly straight-forward with `prebuild` and greatly reduces support requests. I can help if you're interested.

And many thanks for `registry-js`! It's so much better than messing with `reg.exe`, FFI or JScript. I'm using it in [`win-detect-browsers`](https://github.com/vweevers/win-detect-browsers) now, with a 2x performance boost.

PS. Which node versions are supported? My test matrix includes 6, 8, 9 and 10 - no problems so far.

**Comment by shiftkey** [comment]
@vweevers yeah, I am interested if it's easy to add in.

> PS. Which node versions are supported? My test matrix includes 6, 8, 9 and 10 - no problems so far.

I've mostly been focused on targeting Electron, which is 8/9, and not really looked at others (starting some investigating with 10 on some other projects).

**Comment by steventam312** [comment]
I wanna try to help, but I am so new on git or GitHub .

**Comment by shiftkey** [comment]
@steventam312 I'd recommend checking out the `prebuild` package - https://www.npmjs.com/package/prebuild - [`node-keytar`](https://github.com/atom/node-keytar) uses this and we can look at how they have it setup.

**Comment by vweevers** [comment]
Also look at [leveldown](https://github.com/Level/leveldown), which has a simpler setup than `node-keytar` - thanks to [`prebuild-ci`](https://www.npmjs.com/package/prebuild-ci).

(I forgot about this. Haven't got much time but feel free to pull me in for review)

**Comment by shiftkey** [comment]
This took a while to get right thanks to me not remembering how to configure Appveyor, but prebuilt binaries should be available when you upgrade to [`v1.3.2`](https://github.com/desktop/registry-js/releases/tag/v1.3.2) and cover a range of Node and Electron ABIs.
